apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: pod-kill-nginx-schedule
  namespace: chaos-mesh
spec:
  schedule: "0 0 31 2 *" 
  concurrencyPolicy: "Forbid"
  type: PodChaos
  podChaos:
    selector:
      namespaces:
        - test-app
      labelSelectors:
        app: nginx
    action: pod-kill
    mode: one
    duration: "10s"
