apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: nginx-pod-delete
  namespace: test-app
spec:
  appinfo:
    appns: test-app
    applabel: app=nginx
    appkind: Deployment
  chaosServiceAccount: litmus-admin
  experiments:
    - name: pod-delete
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "60"
            - name: CHAOS_INTERVAL
              value: "10"
            - name: FORCE
              value: "true"
---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosSchedule
metadata:
  name: nginx-pod-delete-schedule
  namespace: test-app
spec:
  schedule: "*/1 * * * *"
  timezone: "UTC"
  engineTemplate:
    name: nginx-pod-delete
